---
title: "class07.Rmd"
author: "Jinyoung Park"
date: "1/28/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


These are functions here, look here
```{r}
#Functions

is_both_na <- function(x,y){
  if (length(x)!=length(z)){
    stop("your inputs aren't the same length")
  }
  is.na(x) & is.na(y)
}



rescale_new<- function(x, y) {
 if(length(x) != length(y)) {
 stop("Input x and y should be vectors of the same length")
 }

 na.in.both <- ( is.na(x) & is.na(y) )
 na.number <- sum(na.in.both)
 na.which <- which(na.in.both)
 message("Found ", na.number, " NA's at position(s):",
 paste(na.which, collapse=", ") )

 return( list(number=na.number, which=na.which) )
}
  
  
  
  
  
rescale <- function(x, na.rm=TRUE, plot=FALSE, ...) {
  # Our rescale function from the end of lecture 6
  if( !is.numeric(x)) {
    stop("Input x should be numeric", call.= FALSE)
  }

  if(na.rm) {
    rng <-range(x, na.rm=TRUE)
  } else {
    rng <-range(x)
  }

  answer <- (x - rng[1]) / (rng[2] - rng[1])
  if(plot) { 
    plot(answer, ...) 
  }

  return(answer)
}


rescale2 <- function(x, na.rm=TRUE, plot=FALSE, ...) {
  # Our rescale function from lecture 10

  if( !is.numeric(x) ) {
    stop("Input x should be numeric", call.=FALSE)
  }
  
  rng <-range(x, na.rm=TRUE)

  answer <- (x - rng[1]) / (rng[2] - rng[1])
  if(plot) { 
    plot(answer, ...) 
  }

  return(answer)
}

both_na <- function(x, y) {
  ## Check for NA elements in both input vectors 
  sum( is.na(x) & is.na(y) )
}

both_na2 <- function(x, y) {
  ## Check for NA elements in both input vectors and don't allow re-cycling 
  if(length(x) != length(y)) {
    stop("Input x and y should be vectors of the same length", call.=FALSE)
  }
  sum( is.na(x) & is.na(y) )
}

both_na3 <- function(x, y) {
  ## Print some info on where NA's are as well as the number of them 
  if(length(x) != length(y)) {
    stop("Input x and y should be vectors of the same length", call.=FALSE)
  }
  na.in.both <- ( is.na(x) & is.na(y) )
  na.number  <- sum(na.in.both)
  na.which   <- which(na.in.both)

  message("Found ", na.number, " NA's at position(s):", 
          paste(na.which, collapse=", ") ) 
  
  return( list(number=na.number, which=na.which) )
}


## Find common genes in two lists

df1 <- data.frame(IDs=c("gene1", "gene2", "gene3"),
                  exp=c(2,1,1),
                  stringsAsFactors=FALSE)

df2 <- data.frame(IDs=c("gene2", "gene4", "gene3", "gene5"),
                  exp=c(-2, NA, 1, 2),
                  stringsAsFactors=FALSE)

df3 <- data.frame(IDs=c("gene2", "gene2", "gene5", "gene5"),
                  exp=c(-2, NA, 1, 2),
                  stringsAsFactors=FALSE)

#?intersect
#x <- df1$IDs
#y <- df2$IDs

gene_intersect <- function(x, y) { 
   cbind( x[ x %in% y ], y[ y %in% x ] )
}

gene_intersect2 <- function(df1, df2) { 
   cbind( df1[ df1$IDs %in% df2$IDs, ], 
          df2[ df2$IDs %in% df1$IDs, "exp"] )
}

gene_intersect3 <- function(df1, df2, gene.colname="IDs") { 
   cbind( df1[ df1[,gene.colname] %in% df2[,gene.colname], ], 
          exp2=df2[ df2[,gene.colname] %in% df1[,gene.colname], "exp"] )
}


gene_intersect4 <- function(df1, df2, gene.colname="IDs") { 

  df1.name <- df1[,gene.colname]
  df2.name <- df2[,gene.colname]

  df1.inds <- df1.name %in% df2.name
  df2.inds <- df2.name %in% df1.name

   cbind( df1[ df1.inds, ], 
          exp2=df2[ df2.inds, "exp"] )
}
```


```{r}
#x <- c( 1, 2, NA, 3, NA)
#y <- c(NA, 3, NA, 3, 4)
#z <- c(1,1)
#is_both_na(x,z)

```

source("http://tinyurl.com/rescale-R")


```{r}
x <- df1$IDs
y <- df2$IDs

intersect(x,y)

x %in% y
x
x [x %in% y]

y
y %in% x
y [y %in% x]


cbind(x [x %in% y],y [y %in% x])

```

```{r}
gene_intersect <- function(x,y) {
  cbind(x [x %in% y],y [y %in% x])
}

gene_intersect(x,y)
```

```{r}
gene_intersect <- function(x,y) {
  cbind(x [x %in% y],y [y %in% x])
}

gene_intersect2 <- function(df1,df2) {
  cbind(df1[df1$IDs %in% df2$IDs, ], 
        df2[df2$IDs %in% df1$IDs, ], "exp")
}

gene_intersect3 <- function(df1,df2, gene.colname = "IDs") {
  
  cbind(df1[df1$IDs %in% df2$IDs, ], 
        df2[df2$IDs %in% df1$IDs, ], "exp")
}

gene_intersect4 <- function(df1,df2, gene.colname = "IDs") {
  
  df1.name <- df1[,gene.colname]
  df2.name <- df2[,gene.colname]  
  
  df1.index <- df1.name %in% df2.name
  df2.index <- df2.name %in% df1.name
  
  cbind(df1[df1.index, ], 
        df2[df2.index, ], "exp")
}


#gene_intersect4(df1,df2, gene.colname = "new_names")

df1$IDs
df1[,"IDs"]
gene.colname = "IDs"
#df1[,gene.colname = "new_names"]

colnames(df1) <- c("new_names", "exp")
df1
colnames(df2) <- c("new_names", "exp")
df2

x <- df1$IDs
y <- df2$IDs
gene_intersect(x,y)

#gene_intersect2(df1,df2)

#gene_intersect3(df1,df2, gene.colname = "exp")

```


```{r}
#install.packages("ggplot2")
```


#```{r}
library(ggplot2)
dim(iris)
head(iris)

ggplot(data=iris, aes(x= Sepal.Length, y=Sepal.Width)) 

ggplot(data=iris, aes(x= Sepal.Length, y=Sepal.Width)) + geom_point(size = 3)

ggplot(data=iris, aes(x= Sepal.Length, y=Sepal.Width)) + geom_point(aes(shape = Species),size = 3)


ggplot(data=iris, aes(x= Sepal.Length, y=Sepal.Width)) + geom_point(aes(shape = Species),size = 3) + geom_smooth(method="lm")




```

